#!/usr/bin/env node
/**
 * Build step: inject the Google Solar/Maps API key into a generated config.js.
 *
 * Key resolution order:
 *   1. process.env.GOOGLE_SOLAR_API_KEY  (e.g. Vercel project env var)
 *   2. GOOGLE_SOLAR_API_KEY in a local .env file (committed by you, if desired)
 *
 * The generated config.js is loaded by index.html and exposes the key as
 * window.APP_CONFIG.GOOGLE_API_KEY. If no key is found, an empty config is
 * written and the app falls back to the in-app key field (localStorage).
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const ENV_FILE = path.join(ROOT, ".env");
const OUT_FILE = path.join(ROOT, "config.js");

function readDotEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const dotenv = readDotEnv(ENV_FILE);
const key = (process.env.GOOGLE_SOLAR_API_KEY || dotenv.GOOGLE_SOLAR_API_KEY || "").trim();

const banner = "// AUTO-GENERATED by build.js — do not edit by hand.\n";
const body = "window.APP_CONFIG = " + JSON.stringify({ GOOGLE_API_KEY: key }) + ";\n";
fs.writeFileSync(OUT_FILE, banner + body);

if (key) {
  console.log("build: wrote config.js with GOOGLE_API_KEY (" + key.length + " chars).");
} else {
  console.log("build: no GOOGLE_SOLAR_API_KEY found; wrote empty config.js (app uses in-app key field).");
}
